# Generated by Django 5.0.3 on 2024-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('rollNoId', models.CharField(max_length=9, unique=True)),
                ('email', models.CharField(max_length=9, unique=True)),
                ('semester', models.IntegerField()),
                ('program', models.CharField(default='M.tech', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
    ]
