# Generated by Django 5.0.3 on 2024-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
