# Generated by Django 5.0.3 on 2024-03-14 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_faculty_user_alter_faculty_email'),
        ('students', '0006_alter_student_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNoId', models.CharField(max_length=9, unique=True)),
                ('projectname', models.CharField(default='', max_length=50)),
                ('eval1', models.IntegerField(default=-1)),
                ('eval2', models.IntegerField(default=-1)),
                ('eval3', models.IntegerField(default=-1)),
                ('eval1comment', models.CharField(default='', max_length=100)),
                ('eval2comment', models.CharField(default='', max_length=100)),
                ('eval3comment', models.CharField(default='', max_length=100)),
                ('report1', models.URLField(null=True)),
                ('report2', models.URLField(null=True)),
                ('report3', models.URLField(null=True)),
                ('report1comment', models.CharField(default='', max_length=100)),
                ('report2comment', models.CharField(default='', max_length=100)),
                ('report3comment', models.CharField(default='', max_length=100)),
                ('report1acceptancestatus', models.BooleanField(default=False)),
                ('report2acceptancestatus', models.BooleanField(default=False)),
                ('report3acceptancestatus', models.BooleanField(default=False)),
                ('chair_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_projects', to='faculty.faculty')),
                ('committee_members', models.ManyToManyField(related_name='member_of', to='faculty.faculty')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_projects', to='faculty.faculty')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
